flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- pandoc-citeproc-0.14.1.2
- hslua-0.9.5
- skylighting-0.6
- ansi-terminal-0.7.1.1
- tasty-1.0.0.1
- texmath-0.10.1.1
- tagsoup-0.14.3
ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-10.3
